### ISSUE TITLE
Didn't update registry after move software

### ISSUE THREAD

**Issue by Hou-Xiaoxuan** [MrBeanCpp/ImageViewer2.0#4]
<img width="527" alt="image" src="https://github.com/MrBeanCpp/ImageViewer2.0/assets/59465493/854834bd-36e2-424b-bd6d-07752d79166d">

**Comment by MrBeanCpp** [comment]
Got it, Thank you

**Comment by MrBeanCpp** [comment]
commit dba2650a3795ef94669a0fed22fc6637e91726ed
v1.5.2
